---
- name: Install prometheus
  apt: name={{item}} state=latest update_cache=true cache_valid_time=600
  with_items:
    - prometheus
    - pushgateway
    - alertmanager
    - node-exporter

- name: Create prometheus config
  notify: restart prometheus
  template: src=prometheus.yml dest=/etc/prometheus/prometheus.yml

- name: Create prometheus default config
  notify: restart prometheus
  copy:
    dest: /etc/default/prometheus
    mode: 0755
    content: |
      DAEMON_ARGS="-alertmanager.url=http://localhost:9093"
      # Only 1GB of RAM
      DAEMON_ARGS="$DAEMON_ARGS -storage.local.memory-chunks=102400"
      DAEMON_ARGS="$DAEMON_ARGS -storage.local.max-chunks-to-persist=102400"
      # Keep a year of data
      DAEMON_ARGS="$DAEMON_ARGS -storage.local.retention=525600h"
      # Make links work
      DAEMON_ARGS="$DAEMON_ARGS -web.external-url=http://demo.robustperception.io:9090/"
      # Security
      DAEMON_ARGS="$DAEMON_ARGS -web.enable-remote-shutdown=false"

- name: Create menu.lib
  copy: src=menu.lib dest=/etc/prometheus/console_libraries/menu.lib

- name: Copy consoles
  copy: src={{item}} dest=/etc/prometheus/consoles/{{item}}
  with_items:
    - index.html
    - life.html

- name: Copy rules
  notify: restart prometheus
  copy: src={{item}} dest=/etc/prometheus/{{item}}
  with_items:
    - alert.rules
    - life.rules

- meta: flush_handlers

- name: Start prometheus
  service: name=prometheus state=started enabled=yes
- name: Start pushgateway
  service: name=pushgateway state=started enabled=yes
- name: Start alertmanager
  service: name=alertmanager state=started enabled=yes
- name: Start node-exporter
  service: name=node-exporter state=started enabled=yes

